[package]
name = "ethereum_runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.10", features = ["derive"] }
toml = "0.5.9"
serde = "1.0"
serde_derive = "1.0.136"
