[bin]
geth_dir = "C:/Users/25412/go/bin/geth.exe"
puppeth_dir = "C:/Users/25412/go/bin/puppeth.exe"

[node]
dir = "nodes"
count = 9
sealer_count = 4
connection = [
    [4,5,6],
    [4,6,7],
    [4,7,8],
    [4,5,8],
    [0,1,2,3],
    [0,3],
    [0,1],
    [1,2],
    [2,3]
]
# connection = [[]]

[init]
accounts_dir = "nodes/accounts.toml"

[run]
accounts_dir = "nodes/accounts.toml"

[remote]
ip = "192.168.244.133"
username = "huxw"
pw_file = ""
